name: 🐛 Bug Report
description: Report a bug to help us improve DankDeals MN
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        **Note:** You can mention @claude in your issue description to get AI-powered assistance with debugging and solutions.

  - type: input
    id: browser
    attributes:
      label: Browser/Environment
      description: What browser and version are you using?
      placeholder: "Chrome 120, Safari 17, Mobile Safari iOS 17, etc."
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      description: What device are you using?
      placeholder: "Desktop, iPhone 15, Samsung Galaxy S23, etc."
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any errors in the browser console (F12 -> Console)
      placeholder: Paste any console errors here
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (cosmetic issue, minor inconvenience)
        - Medium (affects functionality but has workaround)
        - High (major functionality affected, no workaround)
        - Critical (app unusable, security issue)
    validations:
      required: true

  - type: checkboxes
    id: affected-areas
    attributes:
      label: Affected Areas
      description: Which parts of the application are affected?
      options:
        - label: Age verification
        - label: User authentication
        - label: Product browsing
        - label: Shopping cart
        - label: Checkout process
        - label: User profile
        - label: Order tracking
        - label: Mobile experience
        - label: Performance

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help