// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Production environment validation
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const errorMessage = 'Missing required Supabase environment variables. Please check your .env configuration.';
  
  if (import.meta.env.DEV) {
    console.error(errorMessage);
    console.error('Required variables: VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY');
  }
  
  throw new Error(errorMessage);
}

// Validate URL format in production
if (import.meta.env.PROD) {
  try {
    new URL(SUPABASE_URL);
  } catch {
    throw new Error('Invalid VITE_SUPABASE_URL format');
  }
  
  // Ensure we're not using example/placeholder values
  if (SUPABASE_URL.includes('your-project') || SUPABASE_PUBLISHABLE_KEY.includes('your-')) {
    throw new Error('Production environment detected but using placeholder Supabase credentials');
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});