name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly on Monday
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Update npm dependencies
        run: |
          npx npm-check-updates -u --target minor
          npm install
          npm audit fix --audit-level=moderate || true
      
      - name: Run tests
        run: |
          npm run lint || true
          npm run type-check || true
          npm run test:unit || true
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            ## Automated Dependency Updates
            
            This PR contains automated dependency updates.
            
            ### Changes
            - Updated npm dependencies to latest minor versions
            - Applied security fixes where available
            
            ### Checklist
            - [ ] Tests pass
            - [ ] Build succeeds
            - [ ] No breaking changes identified
          branch: deps/automated-update
          delete-branch: true 